include: package:lints/recommended.yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - 'example/**'
    - 'check_urls/**'
linter:
  rules:
    - public_member_api_docs
    - prefer_final_locals
    - prefer_relative_imports
    # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
    - unsafe_html