// Mocks generated by Mockito 5.0.7 from annotations
// in rxdart_ext/test/controller/add_null_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'add_null_test.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [VoidController].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoidController extends _i1.Mock implements _i2.VoidController {
  MockVoidController() {
    _i1.throwOnMissingStub(this);
  }
}
